clean_method: pick_zscore
clean_kwargs:
  pick_property: group_name
  options: [BE0, BE1]
fmin: 1
fmax: 100
filter_kwargs:
  copy: True
theta_min: 6
theta_max: 12
delta_min: 1.5
delta_max: 4
psd_scale: decibels
image_format: png
cfg_base_dir: H:\SubRet_recordings_imaging
number_of_shuffles_sta: 5
do_spectrogram_plot: False
loader: neurochat
loader_kwargs:
  system: Axona
  pos_extension: [.txt, .pos]
plot_psd: True
z_score_threshold: 1.1
