cfg_base_dir: H:\SubRet_recordings_imaging
do_spectrogram_plot: False
plot_psd: True
image_format: png
loader: neurochat
loader_kwargs:
  system: Axona
  pos_extension: [.txt, .pos]
clean_method: pick_zscore
clean_kwargs:
  pick_property: group_name
  options: [BE0, BE1]
can_clean_kwargs:
  pick_property: group_name
  options: [TT0, TT1, TT2, TT3, TT4, TT5, TT6, TT7, BE0, BE1]
z_score_threshold: 1.1
fmin: 0.5
fmax: 120
filter_kwargs:
  copy: True
theta_min: 6
theta_max: 12
delta_min: 1.0
delta_max: 4
low_gamma_min: 40
low_gamma_max: 80
high_gamma_min: 80
high_gamma_max: 120
beta_min: 15
beta_max: 30
psd_scale: decibels
number_of_shuffles_sta: 5
num_spike_shuffles: 50
max_psd_freq: 120
max_fooof_freq: 120
notch_freqs: [50, 60, 100]
speed_theta_samples_per_second: 5
max_speed: 40
tmaze_minf: 2.0
tmaze_maxf: 120.0
tmaze_winsec: 0.25
max_lfp_lengths:
  choice: [0.8, 0.2]
  start: 1.0
  end: 1.0
tmaze_egf: False
spindles_use_avg: False
use_first_two_for_ripples: False
lfp_ripple_rate: 1600
min_sleep_length: 60
only_kay_detect: False
except_nwb_errors: True
sleep_join_tol: 0.0
sleep_max_interval_size: 300
