clean_method: pick_zscore
clean_kwargs:
  pick_property: group_name
  options: [BE0, BE1]
can_clean_kwargs:
  pick_property: group_name
  options: [TT0, TT1, TT2, TT3, TT4, TT5, TT6, TT7, BE0, BE1]
fmin: 1
fmax: 100
filter_kwargs:
  copy: True
theta_min: 6
theta_max: 12
delta_min: 1.5
delta_max: 4
psd_scale: decibels
image_format: png
cfg_base_dir: H:\SubRet_recordings_imaging
number_of_shuffles_sta: 5
do_spectrogram_plot: False
loader: neurochat
loader_kwargs:
  system: Axona
  pos_extension: [.txt, .pos]
plot_psd: True
z_score_threshold: 1.2
max_psd_freq: 30
speed_theta_samples_per_second: 5
max_speed: 40
num_spike_shuffles: 40
