rat:
  [
    CSR1,
    CSR2_sham,
    CSR3_sham,
    CSR4,
    CSR5_sham,
    CSR6,
    LSR1,
    LSR2,
    LSR3,
    LSR4,
    LSR5,
    LRS1,
    CRS1,
    CRS2,
  ]
habituation_screening: [0]
maze: [tmaze]
